server:
  port: 8085
 
spring:
  datasource:
        url: jdbc:mysql://35.244.25.10/2016?useSSL=false
        username: root
        password: skcc
        driver-class-name: com.mysql.jdbc.Driver
        
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    
  thymeleaf:
    prefix: classpath:/static/html/
    mode: LEGACYHTML5